/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:864805d1-779b-4fcb-9883-7323c3ba9ff7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_X2dF1gzkH",
    "aws_user_pools_web_client_id": "2pa81vt6np28ihpdqa26psb3rb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://orqgnfwilff35o7p6x3zgja7pe.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-skghr3hts5fc3mwnktoysgmmsa",
    "aws_user_files_s3_bucket": "amplifyappstart4b4f281adadb41e0be1b7dcd2b5a3706100502-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
